name: CMake Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: "3.29.6"

    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libsdl3-dev

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: brew install sdl3

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: choco install sdl3

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

